Repository marcinpiasek128/Projekt_zespolowy, pull requests merged in 2022-03, with the labels that each got.

#13 zmiany
  index.php
  php/home.php
  php/login.php
  php/ranking.php
  php/signup.php
  scripts/jquery.js
  scripts/reload.js
Labels: www, js

#20 Naprawione
  index.php
  php/logout.php
  php/ranking.php
Labels: php

#22 baza v1.0
  database/moviehub.sql
Labels: Baza Danych
